language: r

cache: packages

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
  
addons:
  apt:
    packages:
    - libapparmor-dev
    - libcurl4-openssl-dev
    - openjdk-8-jre
    
r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'